// Mocks generated by Mockito 5.4.6 from annotations
// in wtf_yandex_sirius/test/features/board/board_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wtf_yandex_sirius/features/board/models/comment_model.dart'
    as _i4;
import 'package:wtf_yandex_sirius/features/board/repositories/board_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BoardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoardRepository extends _i1.Mock implements _i2.BoardRepository {
  MockBoardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.CommentModel>> watchBoardComments(String? ownerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchBoardComments,
          [ownerId],
        ),
        returnValue: _i3.Stream<List<_i4.CommentModel>>.empty(),
      ) as _i3.Stream<List<_i4.CommentModel>>);

  @override
  _i3.Future<void> deleteComment(String? commentId) => (super.noSuchMethod(
        Invocation.method(
          #deleteComment,
          [commentId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> markAsRead(String? commentId) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [commentId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> toggleReaction({
    required String? commentId,
    required String? reactionKey,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleReaction,
          [],
          {
            #commentId: commentId,
            #reactionKey: reactionKey,
            #userId: userId,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
