include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - ios/DerivedData/**
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    avoid_print: true

formatter:
  trailing_commas: preserve