// Mocks generated by Mockito 5.4.6 from annotations
// in wtf_yandex_sirius/test/features/search/search_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wtf_yandex_sirius/features/profile/models/profile_model.dart'
    as _i4;
import 'package:wtf_yandex_sirius/features/search/models/search_history_item.dart'
    as _i5;
import 'package:wtf_yandex_sirius/features/search/repositories/search_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepository extends _i1.Mock implements _i2.SearchRepository {
  MockSearchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ProfileModel>> searchByUsername(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByUsername,
          [query],
        ),
        returnValue:
            _i3.Future<List<_i4.ProfileModel>>.value(<_i4.ProfileModel>[]),
      ) as _i3.Future<List<_i4.ProfileModel>>);

  @override
  _i3.Future<String?> resolveUsername(String? username) => (super.noSuchMethod(
        Invocation.method(
          #resolveUsername,
          [username],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<List<_i5.SearchHistoryItem>> getSearchHistory(String? accountUid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchHistory,
          [accountUid],
        ),
        returnValue: _i3.Future<List<_i5.SearchHistoryItem>>.value(
            <_i5.SearchHistoryItem>[]),
      ) as _i3.Future<List<_i5.SearchHistoryItem>>);

  @override
  _i3.Future<void> addToHistory(
    String? accountUid,
    _i5.SearchHistoryItem? item,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToHistory,
          [accountUid, item],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearHistory(String? accountUid) => (super.noSuchMethod(
        Invocation.method(
          #clearHistory,
          [accountUid],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
